CREATE TABLE VEHICLE (
V_ID  VARCHAR(30) NOT NULL,
V_model_NAME   VARCHAR(30) NOT NULL,
V_model_YEAR   VARCHAR(30) NOT NULL
);

CREATE TABLE PERSON (
 PERSON_ID VARCHAR(20) NOT NULL,
 PERSON_NAME VARCHAR(20) NOT NULL,
 PERSON_LAST_NAME VARCHAR(20) NOT NULL,
 SSN VARCHAR(20) NOT NULL
);

